// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEPawpcrKHYbKhyqjke7DWv21mzCkFvfw',
    appId: '1:848074464147:web:c457ae17706d7e85fce666',
    messagingSenderId: '848074464147',
    projectId: 'serene-life-6aee9',
    authDomain: 'serene-life-6aee9.firebaseapp.com',
    databaseURL: 'https://serene-life-6aee9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'serene-life-6aee9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxjaUWFEbV5MLXYuCt1k0xAKyyX_BDoT8',
    appId: '1:848074464147:android:600b53c9ac2643ddfce666',
    messagingSenderId: '848074464147',
    projectId: 'serene-life-6aee9',
    databaseURL: 'https://serene-life-6aee9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'serene-life-6aee9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJJKUvNykA_SNDgpWg5yCHoB__QWFaRT4',
    appId: '1:848074464147:ios:f7c910e1db65e7fbfce666',
    messagingSenderId: '848074464147',
    projectId: 'serene-life-6aee9',
    databaseURL: 'https://serene-life-6aee9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'serene-life-6aee9.appspot.com',
    iosBundleId: 'com.example.sereneLife',
  );
}
